### ISSUE TITLE
Update/version to/with current angular-cli

### ISSUE THREAD

**Issue by PaulHindenberg** [awesome-inc/angular-cli#2]
As of now, angular-cli 1.6.3 breaks.

The image should be tagged according to the cli-version used.

I would be happy to submit a PR.

**Comment by mkoertgen** [comment]
Good idea! Maybe we should involve @alex-kuck

**Comment by alex-kuck** [comment]
Good idea! 
Should‘ve already done that, so go ahead.

**Comment by mkoertgen** [comment]
Ok, i think we should take the git tag `SOURCE_BRANCH` for nailing the angular-cli version

- https://docs.docker.com/docker-cloud/builds/advanced/#environment-variables-for-building-and-testing
- https://docs.npmjs.com/cli/install#description

So, something like the following should do it

```Dockerfile
ENV ANGULAR_CLI_VERSION ${SOURCE_BRANCH:-latest}
npm install -g @angular/cli@${ANGULAR_CLI_VERSION}
```

Bad thing is that this won't work with branch names, only valid tags matching the cli version.
Hm, i would not like to add too much of build logic into this. How to avoid? Is there some simple interpolation logic we could take advantage of?

- https://docs.docker.com/engine/reference/builder/#environment-replacement

**Comment by mkoertgen** [comment]
Ok, updated to tagged builds. Currently building 1.6.3...

**Comment by mkoertgen** [comment]
Added an example app in `./myapp`, just a freshly generated `ng new myapp` where the build definitely works.
@PaulHindenberg So a breaking build seems to be related to a dependency compatibility issue. Please review & compare your dependencies versions with the example app.
If this fixes your build we can close this issue, i think.

However, we are definitely lacking karma/chromium support to enable `ng test`. Heading over to this in a new issue.
